VBank/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf import settings


urlpatterns = [
    path('', views.welcome_view, name='welcome'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIRS)

accounts/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views
from . import transactions

app_name = 'accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('sign-up/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('report-issue/', views.report_view, name='report'),
    path('profile/edit/', views.profile_editview, name='profile-edit'),
    path('users/', views.userList, name='users'),
    path('password-change/', views.password_change, name='passwordChange'),
    path('save-money/', transactions.savemoney_view, name='savemoney'),
    path('transaction-hisotry/', transactions.transaction_history, name='history'),
    path('withdraw-money/', transactions.withdrawmoney_view, name='withdrawmoney'),
    path('transfer-money/', transactions.transmoney_view, name='transfermoney'),
    path('transfer-money/verify/', transactions.transverify_view, name='transverify'),
    path('transfer-money/complete/', transactions.transcomplete_view, name='transcomplete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
import random
# Create your models here.

gender = (
    ('Male','Male'),
    ('Female', 'Female'), 
)


def get_secret_num():
    value = random.randint(1111111111, 9999999999)
    return value

class User(AbstractUser):
    pass

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    sec_num = models.IntegerField(default=get_secret_num())
    acc_bal = models.IntegerField(default=0)
    gender = models.CharField(max_length=20, choices=gender, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_account(sender, instance, created, **kwargs):
    if created:
        Account.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_account(sender, instance, **kwargs):
    instance.account.save()



class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    details = models.TextField()

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import User, Account


class LoginForm(forms.Form):
    username = forms.CharField(max_length=15, widget=forms.TextInput)
    password = forms.CharField(max_length=15, widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=40, widget=forms.TextInput)
    last_name = forms.CharField(max_length=40, widget=forms.TextInput)
    username = forms.CharField(max_length=40, widget=forms.TextInput)
    email = forms.EmailField(max_length=40, widget=forms.EmailInput)
    password = forms.CharField(max_length=40, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=40, widget=forms.PasswordInput)

    def clean_data(self):
        data = self.clean_data
        return data
    
    def get_username(self):
        User = get_user_model
        user = self.clean_data.get('username')
        username = User.objects.get(username=user)
        if username.exists:
            raise forms.ValidationError('Username Taken Bruv')
    
    def get_password(self):
        password = self.clean_data.get('password')
        password2 = self.clean_data.get('password2')
        if (password or password2 == '') or (password != password2):
            raise forms.ValidationError('Password error, try again')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['image', 'gender']


class AccountForm(forms.Form):
    account_number = forms.IntegerField()

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout, get_user_model
from .forms import LoginForm, RegisterForm, UserForm, AccountEditForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from .models import User
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.core.mail import send_mail
from .forms import ContactForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/accounts/login')
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('accounts:dashboard')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = PasswordChangeForm(request.user)
    name = 'change_password.html'
    context = {
        'form':form
    }
    return render(request, name, context)
    

# @login_required(login_url='/accounts/login')
def welcome_view(request):
    name = 'welcome.html'
    return render(request, name)

@login_required(login_url='/accounts/login')
def profile_view(request):
    user = request.user
    name = 'profile.html'
    context = {
        'user':user
    }
    return render(request, name)


@login_required(login_url='/accounts/login')
def dashboard(request):
    user = request.user
    name = 'dashboard.html'
    context = {
        'user':user
    }
    return render(request, name)


def logout_view(request):
    logout(request)
    return redirect('welcome')

def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(request, f'Welcome Back {request.user.username}')
                return redirect('accounts:dashboard')
            else:
                messages.success(request, f'Sorry, Account has been deactivated')
                return redirect('welcome')
    name = 'login.html'
    context = {
        'form' : form
    }
    return render(request, name, context)


User = get_user_model()
def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        new_user = User.objects.create_user(username=username, email=email,
        first_name=first_name, last_name=last_name, password=password)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(request, f'Welcome {request.user.username} 60% of your profile has been completed. Try Updating')
                return redirect('accounts:dashboard')
            else:
                messages.success(request, f'Sorry, Account has been deactivated')
                return redirect('welcome')
        return redirect('welcome')
    name = 'login.html'
    context = {
        'form' : form
    }
    return render(request, name, context)


def userList(request):
    qs = User.objects.all()
    name = 'users.html'
    context = {
        'qs':qs
    }
    return render(request, name, context)


def profile_editview(request):
    user_f = UserForm(request.POST or None, instance=request.user)
    acc_f = AccountEditForm(request.POST or None, request.FILES or None, instance=request.user.account)
    if user_f.is_valid and acc_f.is_valid():
        user_f.save()
        acc_f.save()
        messages.success(request, 'Profile edited successfully')
        return redirect('accounts:dashboard')
    name = 'profileedit.html'
    context = {
        'user_f':user_f,
        'acc_f':acc_f
    }
    return render(request, name, context)


def report_view(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        print(request.user.email)
        print(form.cleaned_data['subject'])
        try:
            send_mail(
                form.cleaned_data['subject'],
                form.cleaned_data['message'],
                request.user.email,
                ['suntopmultimedia@gmail.com'],
                fail_silently=False,
            )
        except:
            messages.info(request, 'Error sending Message, Please check connection and try again')
            return redirect('accounts:report')
    name = 'change_password.html'
    context = {
        'form' : form
    }
    return render(request, name, context)

accounts/templates/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-4 bg-light p-4 mx-auto m-4">
    <form method="POST">
        {% csrf_token %}
        {{ form | crispy}}
        <div class="text-center m-4">
            <input type="submit" value="Submit" class="btn btn-danger">
        </div>
    </form>
</div>

{% endblock content %}

accounts/templates/dashboard.html
{% extends 'base.html' %}

accounts/templates/history.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <h1 class="display-4">Transaction History</h1>
            
            <table class="table table-hover">
                <thead>
                {% for obj in qs %}
                  <tr>
                    <th scope="col">{{ obj.details }}</th>
                  </tr>
                </thead>
                {% endfor %}
              </table>
        </div>
    </div>
{% endblock %}

accounts/templates/login.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <style>
        *{
            margin: 0;
        }
    </style>
</head>
<body>

    <div class="col-4 mx-auto p-5 ">
        <a href="{% url 'welcome' %}" class="btn btn-light mb-2">Back</a>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="continue" class="btn btn-secondary">
        </form>
    </div>
    
</body>
</html>

accounts/templates/profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="row">
    <div class="col-8 mx-auto m-5">
        <div class="text-center">
            <img src="{% if user.account.image %}
            {{user.account.image.url }} 
            {% else %}
            {% static 'images/icon.png' %}
            {% endif %}" alt="" width="150px" height="150px" class="rounded-circle">
        </div>
        <div class="row">
            <div class="mx-auto col-6">
                <div class="text-center mt-4">
                    Full Name
                    <h1 class="lead">
                        <b>{{ user.get_full_name }}</b>
                    </h1>
                </div>
                <br>
                <div>
                    <h1 class="lead">
                        <span><b class="float-left">{{ user.username }}</b></span> <span class="float-right">
                            <b>{% if user.account.gender %}
                                {{ user.account.gender }}
                                {% else%}
                                Gender NA
                            {% endif %}
                            </b></span>
                    </h1>
                </div>
                <br><br>
                <div class="text-center">
                    Email
                    <h1 class="lead">
                        {{ user.email }}
                    </h1>
                </div>
                <div class="text-center">
                    <a href="{% url 'accounts:profile-edit' %}" class="btn btn-secondary">Edit Profile</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/profileedit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        <div class="col-6 mx-auto">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_f | crispy }}
                {{ acc_f | crispy }}
                <input type="submit" value="Edit Profile" class="btn btn-secondary">
            </form>
        </div>
    </div>

{%  endblock %}

accounts/templates/saveform.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-3 mx-auto m-5">
        <h4 class="lead text-center">Fill the fields Correctly</h4>
        <br>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="">Amount</label>
                <input type="number" class="form-control" name='amount'>
            </div>
            <div class="form-group">
                <p><b>Enter this token : {{ token }}</b></p>
                <label for="">Token</label>
                <input type="number" class="form-control" name='token'>
                <input type="hidden" class="form-control" name='parsed_token' value="{{token}}">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-secondary" value="save">
            </div>
            
        </form>
    </div>
{% endblock %}

accounts/templates/transfer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-6 mx-auto mt-5">
        <form action="{% url 'accounts:transverify' %}" method="POST">
            {% csrf_token %}
            {{form | crispy}}
            <input type="submit" class="btn btn-secondary">
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/transverify.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6 mx-auto m-5">
            <div>
                <span>Full Name</span>
                <h4 >{{ user_details.user.get_full_name }}</h4>
            </div>
            <div>
                <span>Sec Number</span>
                <h4 >{{ user_details.user.account.sec_num }}</h4>
            </div>
            <div class="row">
                <a href="{% url 'accounts:transfermoney' %}" class="btn btn-danger m-2">Not this User</a>
            </div>
            
        </div>
    </div>
    <div class="row p-0">
        <div class="col-6 mx-auto">
            <form method="POST" action="{% url 'accounts:transcomplete' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">Amount</label>
                    <input type="number" class="form-control" name='amount'>
                </div>
                <div class="form-group">
                    <p><b>Enter this token : {{ token }}</b></p>
                    <label for="">Token</label>
                    <input type="number" class="form-control" name='token'>
                    <input type="hidden" class="form-control" name='parsed_token' value="{{token}}">
                    <input type="hidden" class="form-control" name='acc_num' value="{{acc_num}}">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Continue">
                </div>    
            </form>
    </div>
{% endblock %}

accounts/templates/users.html
{% extends 'base.html' %}
{% block content %}
<div class="row p-2">
    <h4 class="display-4"><b>Customer's List</b></h4>
</div>
<div class="row">
    <div class="col-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">
                        First Name
                    </th>
                    <th scope="col">
                        Last Name
                    </th>
                    <th scope="col">
                        Username
                    </th>
                    <th scope="col">
                        Email
                    </th>
                    <th scope="col">
                        Secret No.
                    </th>
                    <th scope="col">
                        Status
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for obj in qs %}
                <tr>
                    <td>{{ obj.first_name }}</td>
                    <td>{{ obj.last_name }}</td>
                    <td>{{ obj.username }}</td>
                    <td>{{ obj.email }}</td>
                    <td>{{ obj.account.sec_num }}</td>
                    <td>
                        {% if obj.is_active %}
                            <a href="" class="btn btn-danger">Deactivate</a>
                        {% else %}
                            <a href="" class="btn btn-success">Activate</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

accounts/templates/welcome.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    
</head>
<body style='background-color : #eee; padding: auto auto;'>
    <div class="col-3 mx-auto p-5 p-5 text-center">
    {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:dashboard' %}" class="btn btn-secondary">DashBoard</a>
    {% else %}
    
        <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login</a>
        <a href="{% url 'accounts:register' %}" class="btn btn-success">Register</a>
    {% endif %}
    </div>
</body>
</html>